# Generated by Django 2.2.7 on 2019-11-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20191114_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='', null=True),
        ),
    ]
